### ISSUE TITLE
Ambiente de teste não acessível

### ISSUE THREAD

**Issue by rodzadra** [recovieira/bbboletowebservice#1]
Olá, Reginaldo.

O ambiente de teste não está acessível, o de produção está funcional. Creio que o problema sejam as URLs  do ambiente de teste (https://oauth.hm.bb.com.br/oauth/token e https://cobranca.homologa.bb.com.br:7101/registrarBoleto).

**Comment by recovieira** [comment]
Na verdade, a credencial para registro no ambiente de produção é diferente daquela para registro no ambiente de testes. A tentativa de registrar boletos com uma credencial em um ambiente incompatível ocasionará a emissão da mensagem "Identificador ou credencial inválidos" pelo Web Service do Banco do Brasil. Portanto, você precisará obter uma credencial para cada ambiente. Esqueci de comentar isso anteriormente.

Agradeço muito a você, @rodzadra, por me informar sobre essa sua dúvida. Inseri essa informação no README.

Estou à disposição para o que você e outros desenvolvedores precisarem.

**Comment by gamadoleo** [comment]
Bom dia, vocês conseguiram gerar essas chaves onde?

**Comment by rodzadra** [comment]
> Bom dia, vocês conseguiram gerar essas chaves onde?

Se a sua empresa utiliza o Gerenciador Financeiro: https://aapj.bb.com.br/aapj/liemp.bb?codigoTransacao=RBC

ou, se a sua empresa utiliza o Autoatendimento Setor Público: https://aapj.bb.com.br/aapj/ligov.bb?codigoTransacao=RBC

.

**Comment by gamadoleo** [comment]
![image](https://user-images.githubusercontent.com/23720707/94697567-b8377600-030e-11eb-813f-4f9d29a3f04e.png)

sim porem a pagina está com um alerta e não está funcionando:

http://prntscr.com/uqn5du

**Comment by rodzadra** [comment]
@gamadoleo,

O BB está migrando o front-end e vem apresentando algumas instabilidades, pode ser por isso, mas não tenho certeza se é este o problema. Em todo caso, testando aqui no Firefox, deu certo. 

Clique na segunda imagem quebrada que fica entre os títulos "Gerenciado Financeiro" e o aviso "Atenção, sua tela de acesso será alterada em breve" e entre com sua chave J e senha.

![imagem_quebrada](https://user-images.githubusercontent.com/936497/94700930-6e508f00-0312-11eb-8e33-f1cbda42c53e.png)


.

**Comment by gamadoleo** [comment]
ok, deu certo... agora seria interesante ter no menu do internet banking, pois se já esta com esse aviso vai que a url saia do ar...
valeu.
