### ISSUE TITLE
Endpoints?

### ISSUE THREAD

**Issue by gamadoleo** [recovieira/bbboletowebservice#2]
Bom dia, gostaria de saber de você se conseguiu acesso a outros endpoints, pois pelo que vi no manual e no que você conseguiu integrar só existe o endpoint para registro, nada referente a consultas ou confirmação de pagamento nem mesmo por arquivo retorno, aproveito para lhe perguntar se continua utilizando este meio de integração ou consegiu outro? pois no site de validação de arquivos remessas do bb existe uma documentação para integração por meio de REST:

https://gmtedi.bb.com.br/gmt-sia-api/download/Sistema_Integracao_via_Arquivos_BB_SIA_BB_v2019003.pdf

já tentou realizar a integração desta documentação acima? o interessante dela é que permite tanto o envio de arquivos remessas como obtenção de retorno.

Grato,
gamadoleo@hotmail.com

**Comment by recovieira** [comment]
Olá, @gamadoleo

Quando eu estava escrevendo esse código-fonte, tentei priorizar a funcionalidade de registro de boletos. De qualquer forma, achei a sua ideia interessante. Portanto, espero conseguir disponibilizar, muito em breve, uma nova versão com outras funcionalidades, incluindo essas que você mencionou.


Agradeço pela atenção e sugestão.
