### ISSUE TITLE
Obtenção das credenciais

### ISSUE THREAD

**Issue by gamadoleo** [recovieira/bbboletowebservice#3]
Tem algum aplicativo do bb onde podemos gerar essas credenciais client_id e client_secret, pois é uma dificuldade via agencia.?

**Comment by rodzadra** [comment]
@gamadoleo,

Se a sua empresa utiliza o Gerenciador Financeiro: https://aapj.bb.com.br/aapj/liemp.bb?codigoTransacao=RBC

ou, se a sua empresa utiliza o Autoatendimento Setor Público: https://aapj.bb.com.br/aapj/ligov.bb?codigoTransacao=RBC

.

**Comment by gamadoleo** [comment]
![image](https://user-images.githubusercontent.com/23720707/94698207-73f8a580-030f-11eb-937f-f085f716f7d5.png)
a pagina está com uma mensagem de erro veja:
